id: P7E059A25
initial_creation_type: input
source_metadata:
  title: Kṣitigarbha Series
  language: en
  description: 'Texts related to Kṣitigarbha (sa’i snying po), one of the eight great
    bodhisattvas:'
  volume:
    6a36a83c7b114b0f84e6160113210566:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    a02075bb936c4678a9dbfb1c1fb677e2:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
created_at: '2022-03-01T04:05:33.138127'
last_modified_at: '2022-03-01T04:05:33.138133'
